#!/bin/sh
w -fh > log
num=0

while read line
    do
	num='expr $num + 1'
    done < log

if [ "$num" \> "1" ]
    then
	output=''
	while read line
	do
		output=$line
	done < log
	echo "$output"
	rm log
	exit 2
fi

rm log
